server:
  port: 8080

shop:
  status:
    - http://localhost:8081/application/status
    - http://localhost:8082/application/status
  good:
    - http://localhost:8081/shop/good
    - http://localhost:8082/shop/good
